export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const GET_ERRORS = 'GET_ERRORS';

export const ADD_IMAGE_SUCCESS = 'ADD_IMAGE_SUCCESS';
export const LOAD_IMAGES_SUCCESS = 'LOAD_IMAGES_SUCCESS';
export const UPADTE_IMAGE_SUCCESS = 'UPADTE_IMAGE_SUCCESS';
export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS';
